# Generated by Django 5.2.8 on 2025-11-22 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens used for this message')),
                ('has_analysis_job', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata (e.g., file references, analysis parameters)', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('STATISTICAL', 'Statistical Analysis'), ('VARIANT_INTERPRETATION', 'Variant Interpretation'), ('COMPARATIVE', 'Comparative Analysis'), ('GENETIC_MODEL', 'Genetic Model Filtering'), ('CUSTOM_QUERY', 'Custom Query'), ('REPORT_GENERATION', 'Report Generation')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('parameters', models.JSONField(help_text='Analysis parameters and configuration')),
                ('sample_ids', models.JSONField(default=list, help_text='List of sample IDs to analyze')),
                ('result_data', models.JSONField(blank=True, help_text='Analysis results', null=True)),
                ('result_file_path', models.CharField(blank=True, help_text='Path to generated report file', max_length=500, null=True)),
                ('result_file_type', models.CharField(blank=True, choices=[('html', 'HTML'), ('csv', 'CSV'), ('xlsx', 'Excel')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_job', to='ai_agent.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='ai_agent.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='ai_agent_ch_user_id_268982_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='ai_agent_ch_session_6c0874_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['session', '-created_at'], name='ai_agent_an_session_77dd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', '-created_at'], name='ai_agent_an_status_4eea74_idx'),
        ),
    ]
