# Generated by Django 5.2.8 on 2025-11-14 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(help_text='Gene symbol (e.g., ATP8B1, BRCA1)', max_length=200, verbose_name='Search Term')),
                ('phenotypes', models.JSONField(blank=True, help_text='Human Phenotype Ontology phenotype terms', null=True, verbose_name='HPO Phenotypes')),
                ('diseases', models.JSONField(blank=True, help_text='Diseases associated with the gene from HPO database', null=True, verbose_name='Associated Diseases')),
                ('gene_info', models.JSONField(blank=True, help_text='Gene metadata from HPO', null=True, verbose_name='Gene Information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cache_expires_at', models.DateTimeField(blank=True, help_text='When cached results should be refreshed (default 7 days)', null=True, verbose_name='Cache Expires At')),
                ('success', models.BooleanField(default=True, help_text='Whether the search was successful', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_searches', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Smart Search Query',
                'verbose_name_plural': 'Smart Search Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search_term'], name='smart_searc_search__b68355_idx'), models.Index(fields=['user', '-created_at'], name='smart_searc_user_id_32b744_idx'), models.Index(fields=['cache_expires_at'], name='smart_searc_cache_e_a4854d_idx')],
            },
        ),
    ]
