# Generated by Django 5.2.8 on 2025-11-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesearchquery',
            name='is_pharmvar_gene',
            field=models.BooleanField(default=False, help_text='Whether this gene is a PharmGKB pharmacogenomics variant gene', verbose_name='Is PharmVar Gene'),
        ),
    ]
