# Generated by Django 5.2.8 on 2025-11-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(db_index=True, help_text='Disease identifier (e.g., OMIM:123456)', max_length=50, unique=True, verbose_name='Database ID')),
                ('disease_name', models.CharField(help_text='Name of the disease', max_length=500, verbose_name='Disease Name')),
                ('database', models.CharField(default='OMIM', help_text='Source database (OMIM, ORPHA, DECIPHER, etc.)', max_length=50, verbose_name='Database')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'ordering': ['disease_name'],
                'indexes': [models.Index(fields=['database_id'], name='smart_searc_databas_45f41d_idx'), models.Index(fields=['database'], name='smart_searc_databas_48050b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrez_id', models.IntegerField(db_index=True, help_text='NCBI Entrez Gene ID', unique=True, verbose_name='Entrez Gene ID')),
                ('gene_symbol', models.CharField(db_index=True, help_text='Official gene symbol (e.g., ATP8B1)', max_length=50, verbose_name='Gene Symbol')),
            ],
            options={
                'verbose_name': 'Gene',
                'verbose_name_plural': 'Genes',
                'ordering': ['gene_symbol'],
                'indexes': [models.Index(fields=['entrez_id'], name='smart_searc_entrez__c0dc65_idx'), models.Index(fields=['gene_symbol'], name='smart_searc_gene_sy_dd2f76_idx')],
            },
        ),
        migrations.CreateModel(
            name='HPOTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpo_id', models.CharField(db_index=True, help_text='HPO term identifier (e.g., HP:0000001)', max_length=20, unique=True, verbose_name='HPO ID')),
                ('name', models.CharField(help_text='Human-readable name of the phenotype', max_length=500, verbose_name='Term Name')),
                ('definition', models.TextField(blank=True, help_text='Description of the phenotype term', null=True, verbose_name='Definition')),
            ],
            options={
                'verbose_name': 'HPO Term',
                'verbose_name_plural': 'HPO Terms',
                'ordering': ['hpo_id'],
                'indexes': [models.Index(fields=['hpo_id'], name='smart_searc_hpo_id_55aef5_idx'), models.Index(fields=['name'], name='smart_searc_name_b0b549_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneDiseaseAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_associations', to='smart_search.disease', verbose_name='Disease')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_associations', to='smart_search.gene', verbose_name='Gene')),
            ],
            options={
                'verbose_name': 'Gene-Disease Association',
                'verbose_name_plural': 'Gene-Disease Associations',
                'indexes': [models.Index(fields=['gene', 'disease'], name='smart_searc_gene_id_56c44f_idx')],
                'unique_together': {('gene', 'disease')},
            },
        ),
        migrations.CreateModel(
            name='GenePhenotypeAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenotype_associations', to='smart_search.gene', verbose_name='Gene')),
                ('hpo_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_associations', to='smart_search.hpoterm', verbose_name='HPO Term')),
            ],
            options={
                'verbose_name': 'Gene-Phenotype Association',
                'verbose_name_plural': 'Gene-Phenotype Associations',
                'indexes': [models.Index(fields=['gene', 'hpo_term'], name='smart_searc_gene_id_58a553_idx')],
                'unique_together': {('gene', 'hpo_term')},
            },
        ),
        migrations.CreateModel(
            name='DiseasePhenotypeAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, help_text="Frequency of phenotype in disease (e.g., 'Very frequent', '5/10')", max_length=100, null=True, verbose_name='Frequency')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenotype_associations', to='smart_search.disease', verbose_name='Disease')),
                ('hpo_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_associations', to='smart_search.hpoterm', verbose_name='HPO Term')),
            ],
            options={
                'verbose_name': 'Disease-Phenotype Association',
                'verbose_name_plural': 'Disease-Phenotype Associations',
                'indexes': [models.Index(fields=['disease', 'hpo_term'], name='smart_searc_disease_e9721e_idx')],
                'unique_together': {('disease', 'hpo_term')},
            },
        ),
    ]
