# Generated by Django 5.2.8 on 2025-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0002_disease_gene_hpoterm_genediseaseassociation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='database',
            field=models.CharField(default='OMIM', help_text='Source database (OMIM, ORPHA, DECIPHER, etc.)', max_length=100, verbose_name='Database'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='database_id',
            field=models.CharField(db_index=True, help_text='Disease identifier (e.g., OMIM:123456)', max_length=200, unique=True, verbose_name='Database ID'),
        ),
        migrations.AlterField(
            model_name='hpoterm',
            name='hpo_id',
            field=models.CharField(db_index=True, help_text='HPO term identifier (e.g., HP:0000001)', max_length=50, unique=True, verbose_name='HPO ID'),
        ),
    ]
