# Generated by Django 5.2.8 on 2025-11-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0003_alter_disease_database_alter_disease_database_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesearchquery',
            name='search_type',
            field=models.CharField(choices=[('gene', 'Gene'), ('phenotype', 'Phenotype')], default='gene', help_text='Type of search: gene or phenotype', max_length=20, verbose_name='Search Type'),
        ),
        migrations.AlterField(
            model_name='genesearchquery',
            name='search_term',
            field=models.CharField(help_text='Gene symbol (e.g., ATP8B1, BRCA1) or phenotype name', max_length=200, verbose_name='Search Term'),
        ),
    ]
