# Generated by Django 5.2.8 on 2025-12-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0004_genesearchquery_search_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genesearchquery',
            name='search_type',
            field=models.CharField(choices=[('gene', 'Gene'), ('phenotype', 'Phenotype'), ('disease', 'Disease')], default='gene', help_text='Type of search: gene or phenotype', max_length=20, verbose_name='Search Type'),
        ),
    ]
