# Generated by Django 5.2.8 on 2025-12-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0002_add_disease_search_type'),
        ('smart_search', '0005_alter_genesearchquery_search_type'),
    ]

    operations = [
    ]
