# Generated by Django 5.2.8 on 2025-12-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0005_add_clinpgx_data'),
        ('smart_search', '0007_alter_genesearchquery_search_type'),
    ]

    operations = [
    ]
