# Generated by Django 5.2.8 on 2025-12-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0006_add_variant_search'),
        ('smart_search', '0008_merge_20251208_1305'),
    ]

    operations = [
    ]
