# Generated by Django 5.2.8 on 2025-12-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0007_add_clinpgx_variant_data'),
        ('smart_search', '0010_alter_genesearchquery_search_type'),
    ]

    operations = [
    ]
