# Generated by Django 5.2.8 on 2025-12-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0008_add_clinpgx_drug_labels'),
        ('smart_search', '0011_merge_20251208_1438'),
    ]

    operations = [
    ]
