# Generated by Django 5.2.8 on 2025-12-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_search', '0009_add_chemical_models'),
        ('smart_search', '0012_merge_20251209_1208'),
    ]

    operations = [
    ]
