# Generated by Django 5.2.8 on 2025-11-08 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, help_text='Unique identifier for the patient', max_length=50, unique=True, verbose_name='Patient ID')),
                ('name', models.CharField(help_text="Patient's full name (use anonymized ID if required by ethics protocols)", max_length=100, verbose_name='Full Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('clinical_info_json', models.JSONField(default=dict, help_text='Unstructured clinical data in JSON format (e.g., diagnosis, symptoms, lab results, phenotype)', verbose_name='Clinical Information (JSON)')),
                ('main_exome_result', models.CharField(default='Awaiting Analysis', help_text='Summary of the main genomic finding or current analysis status', max_length=255, verbose_name='Main Exome Result')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations about the patient or case', null=True, verbose_name='Research Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('responsible_user', models.ForeignKey(blank=True, help_text="The researcher or clinician responsible for this patient's data", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsible User')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
