# Generated by Django 5.2.8 on 2025-11-08 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Research project or study identifier', max_length=50, verbose_name='Project')),
                ('batch_id', models.CharField(help_text='Sequencing batch identifier', max_length=50, verbose_name='Batch')),
                ('sample_id', models.CharField(db_index=True, help_text='Laboratory sample identifier', max_length=50, verbose_name='Sample ID')),
                ('data_type', models.CharField(choices=[('WGS', 'Whole Genome Sequencing'), ('WES', 'Whole Exome Sequencing'), ('RNA', 'RNA-Seq'), ('PANEL', 'Gene Panel'), ('OTHER', 'Other')], default='WES', max_length=10, verbose_name='Data Type')),
                ('server_name', models.CharField(choices=[('SERVER1', 'BioHub Main Server'), ('SERVER2', 'Burlo Garofolo Archive'), ('SERVER3', 'Backup/FTP Server')], max_length=10, verbose_name='Server Location')),
                ('file_path', models.CharField(help_text='Relative path to the file on the server (internal use only, never exposed to client)', max_length=500, verbose_name='File Path')),
                ('file_type', models.CharField(choices=[('VCF', 'VCF - Variant Call Format'), ('BAM', 'BAM - Binary Alignment Map'), ('FASTQ', 'FASTQ - Raw Sequencing Data'), ('PDF', 'PDF - Analysis Report'), ('TSV', 'TSV - Tabular Data'), ('CRAM', 'CRAM - Compressed Alignment')], default='VCF', max_length=10, verbose_name='File Type')),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, help_text='File size in megabytes for tracking storage usage', max_digits=10, null=True, verbose_name='File Size (MB)')),
                ('checksum', models.CharField(blank=True, help_text='MD5 hash for file integrity verification', max_length=64, null=True, verbose_name='File Checksum (MD5)')),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to soft-delete files without removing database records', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_locations', to='samples.patient', verbose_name='Patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Analysis File Location',
                'verbose_name_plural': 'Analysis File Locations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sample_id', 'file_type'], name='files_analy_sample__08add4_idx'), models.Index(fields=['patient', 'is_active'], name='files_analy_patient_f4456e_idx')],
            },
        ),
    ]
