# Generated by Django 5.2.8 on 2025-11-08 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Name')),
                ('role', models.CharField(choices=[('RESEARCHER', 'Researcher'), ('CLINICIAN', 'Clinician'), ('DATA_MANAGER', 'Data Manager'), ('ADMIN', 'Administrator')], default='RESEARCHER', max_length=20, verbose_name='Role')),
                ('team', models.CharField(choices=[('GENETICS', 'Genetics Department'), ('PEDIATRICS', 'Pediatrics'), ('LAB_DADAMO', "Lab D'Adamo"), ('BIOINFORMATICS', 'Bioinformatics'), ('OTHER', 'Other')], default='LAB_DADAMO', max_length=30, verbose_name='Team/Department')),
                ('institutional_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Institutional Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('institution_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Institution ID')),
                ('profile_completed', models.BooleanField(default=False, verbose_name='Profile Completed')),
                ('approved', models.BooleanField(default=False, verbose_name='Account Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
