# Generated by Django 5.2.8 on 2025-11-13 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneSearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(help_text='Gene name (e.g., ATP8B1, BRCA1), disease name, or drug name', max_length=200, verbose_name='Search Term')),
                ('search_type', models.CharField(choices=[('GENE', 'Gene'), ('DISEASE', 'Disease'), ('DRUG', 'Drug')], default='GENE', max_length=20, verbose_name='Search Type')),
                ('hpo_results', models.JSONField(blank=True, help_text='Human Phenotype Ontology phenotypes and terms', null=True, verbose_name='HPO Results')),
                ('omim_results', models.JSONField(blank=True, help_text='OMIM disease information with IDs and names', null=True, verbose_name='OMIM Results')),
                ('pharmgkb_results', models.JSONField(blank=True, help_text='Pharmacogenetics information (ADME genes, drug response variants)', null=True, verbose_name='PharmGKB Results')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cache_expires_at', models.DateTimeField(blank=True, help_text='When cached results should be refreshed (default 7 days)', null=True, verbose_name='Cache Expires At')),
                ('success', models.BooleanField(default=True, help_text='Whether the search was successful', verbose_name='Success')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_searches', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Gene Search Query',
                'verbose_name_plural': 'Gene Search Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search_term', 'search_type'], name='gene_search_search__7c39bc_idx'), models.Index(fields=['user', '-created_at'], name='gene_search_user_id_66393d_idx'), models.Index(fields=['cache_expires_at'], name='gene_search_cache_e_169186_idx')],
            },
        ),
    ]
