# Generated by Django 5.2.8 on 2025-11-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_workflows', '0004_add_deepvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconfiguration',
            name='minimap2_preset',
            field=models.CharField(blank=True, choices=[('sr', 'Short reads (Illumina)'), ('map-ont', 'Oxford Nanopore'), ('map-pb', 'PacBio CLR'), ('map-hifi', 'PacBio HiFi/CCS'), ('asm5', 'Assembly-to-ref (e95% identity)'), ('asm10', 'Assembly-to-ref (e90% identity)'), ('asm20', 'Assembly-to-ref (e80% identity)')], default='sr', max_length=20, verbose_name='Minimap2 Preset'),
        ),
    ]
