# Generated by Django 5.2.8 on 2025-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_workflows', '0005_alter_workflowconfiguration_minimap2_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconfiguration',
            name='aligner',
            field=models.CharField(choices=[('bwa', 'BWA-MEM'), ('minimap2', 'Minimap2')], default='minimap2', max_length=20, verbose_name='Alignment Tool'),
        ),
    ]
