# Generated by Django 5.2.8 on 2025-11-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region_selection', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='regionextractionjob',
            new_name='region_sele_job_id_4ebec9_idx',
            old_name='region_sele_job_id_4a1b6c_idx',
        ),
        migrations.RenameIndex(
            model_name='regionextractionjob',
            new_name='region_sele_user_id_a8637d_idx',
            old_name='region_sele_user_id_3d8f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='regionextractionjob',
            new_name='region_sele_expires_3cfcdc_idx',
            old_name='region_sele_expires_6c9e1b_idx',
        ),
    ]
