# Generated by Django 5.2.8 on 2025-11-07 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True, verbose_name='ID do Paciente')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('clinical_info_json', models.JSONField(default=dict, help_text='Dados clínicos não estruturados em formato JSON.', verbose_name='Informações Clínicas (JSON)')),
                ('main_exome_result', models.CharField(default='Aguardando Análise', max_length=255, verbose_name='Resultado Principal')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='AnalysisFileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(choices=[('SERVER1', 'Servidor BioHub Principal'), ('SERVER2', 'Servidor Burlo Garofolo (Arquivo Morto)'), ('SERVER3', 'Servidor de Backup/FTP')], max_length=10, verbose_name='Servidor')),
                ('file_path', models.CharField(max_length=255, verbose_name='Caminho do Arquivo')),
                ('file_type', models.CharField(default='VCF', max_length=10, verbose_name='Tipo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_locations', to='users.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Localização do Arquivo de Análise',
                'verbose_name_plural': 'Localizações dos Arquivos de Análise',
            },
        ),
    ]
