# Generated by Django 5.2.8 on 2025-11-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfilelocation',
            name='batch_id',
            field=models.CharField(default='N/D', max_length=50, verbose_name='Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisfilelocation',
            name='data_type',
            field=models.CharField(choices=[('WGS', 'WGS'), ('WES', 'WES'), ('RNA', 'RNA-Seq'), ('OTHER', 'Outro')], default='WES', max_length=10, verbose_name='Tipo de Dado'),
        ),
        migrations.AddField(
            model_name='analysisfilelocation',
            name='project_name',
            field=models.CharField(default='N/D', max_length=50, verbose_name='Projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisfilelocation',
            name='sample_id',
            field=models.CharField(default='N/D', max_length=50, verbose_name='ID da Amostra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisfilelocation',
            name='file_type',
            field=models.CharField(default='VCF', max_length=10, verbose_name='Tipo de Arquivo'),
        ),
    ]
