# Generated by Django 5.2.8 on 2025-11-08 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_analysisfilelocation_batch_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisfilelocation',
            options={'verbose_name': 'Analysis File Location', 'verbose_name_plural': 'Analysis File Locations'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='analysisfilelocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisfilelocation',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='analysisfilelocation',
            name='data_type',
            field=models.CharField(choices=[('WGS', 'Whole Genome Sequencing'), ('WES', 'Whole Exome Sequencing'), ('RNA', 'RNA-Seq'), ('OTHER', 'Other')], default='WES', max_length=10, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='analysisfilelocation',
            name='file_path',
            field=models.CharField(max_length=255, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='analysisfilelocation',
            name='file_type',
            field=models.CharField(choices=[('VCF', 'VCF'), ('BAM', 'BAM'), ('FASTQ', 'FASTQ'), ('PDF', 'PDF Report')], default='VCF', max_length=10, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='analysisfilelocation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_locations', to='users.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='analysisfilelocation',
            name='project_name',
            field=models.CharField(max_length=50, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='analysisfilelocation',
            name='sample_id',
            field=models.CharField(max_length=50, verbose_name='Sample ID'),
        ),
        migrations.AlterField(
            model_name='analysisfilelocation',
            name='server_name',
            field=models.CharField(choices=[('SERVER1', 'BioHub Main Server'), ('SERVER2', 'Burlo Garofolo (Archive)'), ('SERVER3', 'Backup/FTP Server')], max_length=10, verbose_name='Server'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinical_info_json',
            field=models.JSONField(default=dict, help_text='Unstructured clinical data in JSON format.', verbose_name='Clinical Information (JSON)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='main_exome_result',
            field=models.CharField(default='Awaiting Analysis', max_length=255, verbose_name='Main Result'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsible User'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('RESEARCHER', 'Researcher'), ('CLINICIAN', 'Clinician'), ('DATA_MANAGER', 'Data Manager'), ('ADMIN', 'Administrator')], default='RESEARCHER', max_length=20, verbose_name='Role')),
                ('department', models.CharField(choices=[('GENETICS', 'Genetics Department'), ('PEDIATRICS', 'Pediatrics'), ('LAB_DADAMO', "Lab D'Adamo"), ('BIOINFORMATICS', 'Bioinformatics'), ('OTHER', 'Other')], default='LAB_DADAMO', max_length=30, verbose_name='Department')),
                ('institution_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Institution ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('approved', models.BooleanField(default=False, verbose_name='Account Approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
