# Generated by Django 5.2.8 on 2025-11-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_analysisfilelocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnalysisFileLocation',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
