# Generated by Django 5.2.8 on 2025-11-20 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_migrate_role_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('DATA_MANAGER', 'Data Manager'), ('RESEARCHER', 'Researcher'), ('CLINICIAN', 'Clinician')], max_length=20)),
                ('requested_role', models.CharField(choices=[('ADMIN', 'Administrator'), ('DATA_MANAGER', 'Data Manager'), ('RESEARCHER', 'Researcher'), ('CLINICIAN', 'Clinician')], max_length=20)),
                ('reason', models.TextField(help_text='Please explain why you need this role change', verbose_name='Reason for Change')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on this request')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Change Request',
                'verbose_name_plural': 'Role Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
